### PR TITLE
New Scientist-Inspired Webpage (HTML & CSS Foundation)

### PR DESCRIPTION
**Pull request by biodun-ojo**
This pull request lays the groundwork for a webpage inspired by New Scientist's design using HTML and CSS.

- The HTML structure includes sections for a header, navigation bar, article containers, and a footer.
- CSS styles the page with fonts, colors, and basic layout properties to achieve a clean and modern look.

**Note:** This pull request focuses on the HTML and CSS aspects. Images and dynamic content will be addressed in future contributions.

### CODE REVIEW

**Comment by soieducation** [comment]
Hi @biodun-ojo , 

Great work on making the changes requested previously 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
Your Project dosent have a live link.

Your pull request should be descriptive.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by biodun-ojo** [comment]
> Hi @biodun-ojo ,
> 
> Great work on making the changes requested previously 👏 You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
> 
> ## Required Changes ♻️
> Your Project dosent have a live link.
> 
> Your pull request should be descriptive.
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by biodun-ojo** [comment]
> > Hi @biodun-ojo ,
> > Great work on making the changes requested previously 👏 You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
> > ## Required Changes ♻️
> > Your Project dosent have a live link.
> > Your pull request should be descriptive.
> > Cheers and Happy coding!👏👏👏
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by biodun-ojo** [comment]
hi @soieducation 

I have given the development branch a live link as instructed by you and as for my pull request being descriptive i will ensure to continue working on that

**Comment by soieducation** [comment]
Hi @biodun-ojo , 

Great work on making the changes requested previously 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

- Your Project dosent have a live link.
- Your pull request should be descriptive.
- implement a readme file 

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by soieducation** [comment]
Hi @biodun-ojo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 
6vEo

- you can try improve your code and design
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
